/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-111317-ga77f5019f5-20230702"
#endif /* AVUTIL_FFVERSION_H */
